-- PostgreSQL schema scaffold. Demo runtime currently stores profile/documents in memory.
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE profiles (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, attributes JSONB NOT NULL DEFAULT '{}', field_status JSONB NOT NULL DEFAULT '{}', language TEXT NOT NULL DEFAULT 'English', updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE schemes (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL, government TEXT NOT NULL, ministry TEXT, state TEXT NOT NULL, category TEXT NOT NULL, benefits TEXT NOT NULL, eligibility_summary TEXT NOT NULL, application_process TEXT NOT NULL, application_url TEXT NOT NULL, source_url TEXT NOT NULL, source_name TEXT NOT NULL, last_verified DATE NOT NULL, active BOOLEAN NOT NULL DEFAULT true, synthetic BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE eligibility_rules (id BIGSERIAL PRIMARY KEY, scheme_id TEXT NOT NULL REFERENCES schemes(id) ON DELETE CASCADE, field TEXT NOT NULL, operator TEXT NOT NULL, value JSONB, description TEXT NOT NULL, required BOOLEAN NOT NULL DEFAULT true, group_operator TEXT);
CREATE TABLE scheme_documents (id BIGSERIAL PRIMARY KEY, scheme_id TEXT NOT NULL REFERENCES schemes(id) ON DELETE CASCADE, document_type TEXT NOT NULL, required BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE scheme_sources (id BIGSERIAL PRIMARY KEY, scheme_id TEXT NOT NULL REFERENCES schemes(id) ON DELETE CASCADE, source_url TEXT NOT NULL, source_name TEXT NOT NULL, checked_at DATE NOT NULL, notes TEXT);
CREATE TABLE conversations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE messages (id BIGSERIAL PRIMARY KEY, conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK(role IN ('user','assistant')), content TEXT NOT NULL, language TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE user_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, filename TEXT NOT NULL, private_storage_key TEXT NOT NULL, content_type TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE document_extractions (id BIGSERIAL PRIMARY KEY, document_id UUID NOT NULL REFERENCES user_documents(id) ON DELETE CASCADE, extracted_fields JSONB NOT NULL DEFAULT '{}', confidence JSONB NOT NULL DEFAULT '{}', reviewed BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE application_checklists (id BIGSERIAL PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, scheme_id TEXT NOT NULL REFERENCES schemes(id), items JSONB NOT NULL DEFAULT '[]', updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
